# Generated by Django 4.1.13 on 2024-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cur_id", models.CharField(max_length=10, verbose_name="ID")),
                ("num_code", models.IntegerField(verbose_name="NumCode")),
                ("char_code", models.CharField(max_length=3, verbose_name="CharCode")),
                ("nominal", models.IntegerField(verbose_name="Nominal")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="Value"
                    ),
                ),
                (
                    "previous",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="Previous"
                    ),
                ),
            ],
        ),
    ]
