# Generated by Django 4.1.13 on 2024-02-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rates",
            new_name="Rate",
        ),
    ]
