# Generated by Django 4.1.13 on 2024-02-14 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0002_rename_rates_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 14, 23, 8, 25, 877573),
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
    ]
