# Generated by Django 4.1.13 on 2024-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0003_rate_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="value",
        ),
        migrations.AddField(
            model_name="rate",
            name="rate",
            field=models.DecimalField(
                decimal_places=4, default=10, max_digits=7, verbose_name="Rate"
            ),
            preserve_default=False,
        ),
    ]
