# Generated by Django 4.1.13 on 2024-02-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0004_remove_rate_value_rate_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rate",
            old_name="char_code",
            new_name="charcode",
        ),
    ]
